# fly.toml file generated for lively-fire-1522 on 2023-02-09T13:05:43-08:00

app = "lively-fire-1522"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 7781
  processes = ["app"]
  protocol = "udp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 7781
